# Generated by Django 5.2.6 on 2025-12-05 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonateForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('cont_no', models.CharField(max_length=20)),
                ('food_type', models.TextField()),
                ('cdt', models.CharField(max_length=50)),
                ('pdt', models.CharField(max_length=50)),
                ('ploc', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distribution_center', models.CharField(blank=True, max_length=200, null=True)),
                ('distribution_date', models.CharField(blank=True, max_length=50, null=True)),
                ('people_served', models.IntegerField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donateform',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_center', models.CharField(max_length=200)),
                ('distribution_date', models.DateTimeField()),
                ('people_served', models.IntegerField()),
                ('adults', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('senior_citizens', models.IntegerField(default=0)),
                ('satisfaction_rating', models.IntegerField()),
                ('food_quality', models.CharField(choices=[('fresh', 'Fresh'), ('good', 'Good'), ('acceptable', 'Acceptable')], max_length=50)),
                ('hygiene_maintained', models.BooleanField(default=True)),
                ('team_leader_name', models.CharField(max_length=100)),
                ('team_leader_contact', models.CharField(max_length=20)),
                ('volunteers_count', models.IntegerField(default=2)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='donor_api.donateform')),
            ],
            options={
                'db_table': 'distribution_record',
            },
        ),
        migrations.CreateModel(
            name='DonationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='donor_api.donateform')),
            ],
            options={
                'db_table': 'donation_tracker',
            },
        ),
    ]
