# Generated by Django 5.2 on 2026-01-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0003_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_team',
                'ordering': ['name'],
            },
        ),
    ]
