# Generated by Django 5.2 on 2026-01-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0004_deliveryteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('food_type', models.TextField()),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('people_served', models.IntegerField(default=0)),
                ('distribution_center', models.CharField(blank=True, max_length=200, null=True)),
                ('distribution_date', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('impact_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='generated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='donor_api.donateform')),
            ],
            options={
                'db_table': 'donation_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
