# Generated by Django 5.2 on 2026-01-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_api', '0005_donationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateform',
            name='food_photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_donations/'),
        ),
        migrations.AddField(
            model_name='donateform',
            name='preparation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donateform',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
    ]
